### ISSUE TITLE
erro ao instalar

### ISSUE THREAD

**Issue by LucasSaud** [guilhermejansen/whaticket_deep_cleaning#1]
Configurando PM2 para manter a aplicação rodando em segundo plano...
[PM2][ERROR] Script not found: /home/deploy/cleaning/scripts/whaticket_deep_cleaning/dist/index.js
[PM2] Saving current process list...
[PM2] Successfully saved in /home/deploy/.pm2/dump.pm2
[PM2] Init System found: systemd
[PM2] To setup the Startup Script, copy/paste the following command:
sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u deploy --hp /home/deploy
Aplicação instalada e configurada para iniciar automaticamente após o boot do sistema.
deploy@debruin-server:~/cleaning/scripts$

**Comment by guilhermejansen** [comment]
Ainda não conclui o desenvolvimento, aguarde atualizações.
